file_path: test.csv
transform_type: dynamodb # enum: dynamodb, parquet, json, csv
batch_size: 10 # (optional) default: process 5 partitions at a time
partition_size: 100000
segment_size: 10000
schema:
  table_name: Products # (optional) required for dynamodb
  key: id # (optional) required for dynamodb
  fields:
    - id: string
    - name: string
    - price: number
    - in_stock: bool
# partition_dir: partitions # (optional) default: partitions
# output_dir: output # (optional) default: output
# delimiter: "," # (optional) default: comma (",")
