name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    env:
      NAME: etl

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: |
          GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o ${{ env.NAME }}_${{ matrix.os }}_${{ matrix.arch }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.NAME }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ env.NAME }}_${{ matrix.os }}_${{ matrix.arch }}
